[package]
name = "anime-games-launcher"
version = "1.0.0"
description = "Anime Games Launcher"
authors = ["Nikita Podvirnyy <krypt0nn@vk.com>"]
homepage = "https://github.com/an-anime-team/anime-games-launcher"
repository = "https://github.com/an-anime-team/anime-games-launcher"
license = "GPL-3.0"
edition = "2021"
build = "build.rs"

[profile.release]
strip = true
lto = true
opt-level = "s"

[profile.profiling]
inherits = "release"
strip = false
debug = true

[build-dependencies]
glib-build-tools = "0.18.0"

[dependencies.relm4]
version = "0.7.0-beta.2"
features = ["macros", "libadwaita"]

[dependencies.gtk]
package = "gtk4"
version = "0.7.3"
features = ["v4_12"]

[dependencies.adw]
package = "libadwaita"
version = "0.5.3"
features = ["v1_4"]

[dependencies.anime-game-core]
# git = "https://github.com/an-anime-team/anime-game-core"
# branch = "v2.0.0-rewrite"
path = "../anime-game-core"

# [dependencies.rfd]
# version = "0.11"
# features = ["xdg-portal"]
# default-features = false

[dependencies]
serde = { version = "1.0.194", features = ["derive"] }
serde_json = "1.0.110"

anyhow = { version = "1.0.79", features = ["backtrace"] }
lazy_static = "1.4.0"
flume = "0.11.0"
rusty_pool = "0.7.0"
num_cpus = "1.16.0"

wincompatlib = { version = "0.7.4", features = ["all"] }

mlua = { version = "0.9.2", features = ["luajit", "vendored", "serialize"] }
