[package]
name = "anime-games-launcher"
version = "1.0.1"
description = "Anime Games Launcher"
authors = ["Nikita Podvirnyy <krypt0nn@vk.com>"]
homepage = "https://github.com/an-anime-team/anime-games-launcher"
repository = "https://github.com/an-anime-team/anime-games-launcher"
license = "GPL-3.0"
edition = "2021"
build = "build.rs"

[profile.release]
strip = true
lto = true
opt-level = "s"

[profile.profiling]
inherits = "release"
strip = false
debug = true

[build-dependencies]
glib-build-tools = "0.18.0"

[dependencies.relm4]
version = "0.7.0-beta.2"
features = ["macros", "libadwaita"]

[dependencies.gtk]
package = "gtk4"
version = "0.7.3"
features = ["v4_12"]

[dependencies.adw]
package = "libadwaita"
version = "0.5.3"
features = ["v1_4"]

[dependencies.anime-game-core]
git = "https://github.com/an-anime-team/anime-game-core"
branch = "v2.0.0-rewrite"
# path = "../anime-game-core"

# [dependencies.rfd]
# version = "0.11"
# features = ["xdg-portal"]
# default-features = false

[dependencies]
serde = { version = "1.0.194", features = ["derive"] }
serde_json = "1.0.110"

anyhow = { version = "1.0.79", features = ["backtrace"] }
lazy_static = "1.4.0"
flume = "0.11.0"
rusty_pool = "0.7.0"
num_cpus = "1.16.0"
cached = "0.47.0"
human-panic = "1.2.2"
chrono = "0.4.31"

tracing = "0.1.40"
tracing-subscriber = "0.3.18"

fluent-templates = "0.8.0"
unic-langid = "0.9.4"

wincompatlib = { version = "0.7.4", features = ["all"] }
open = "5.0.1"

mlua = { version = "0.9.4", features = ["luajit", "vendored", "serialize"] }

md-5 = { version = "0.10.6", features = ["asm"] }
sha1 = { version = "0.10.6", features = ["asm"] }
xxhash-rust = { version = "0.8.8", features = ["xxh32", "xxh64", "xxh3"] }
crc32fast = "1.3.2"
